services:
  postgres:
    image: postgres:15
    container_name: postgres-netflix
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-netflix-db.sh:/docker-entrypoint-initdb.d/init-netflix-db.sh
      - ./postgres-sample-dbs:/postgres-sample-dbs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data: